vim.opt.listchars = {
	-- eol = "↴",
	trail = "."
}

require("indent_blankline").setup {
	show_end_of_line = true,
	char = "│",
	buftype_exclude = { "terminal", "nofile" },
	show_trailing_blankline_indent = false,
	show_first_indent_level = false,
	use_treesitter = false,
	show_current_context = true,
	context_patterns = {
		"class",
		"return",
		"function",
		"method",
		"^if",
		"^do",
		"^switch",
		"^while",
		"jsx_element",
		"^for",
		"^object",
		"^table",
		"block",
		"arguments",
		"if_statement",
		"else_clause",
		"jsx_element",
		"jsx_self_closing_element",
		"try_statement",
		"catch_clause",
		"import_statement",
		"operation_type",
	},
	filetype_exclude = {
		"log",
		"gitcommit",
		"vimwiki",
		"markdown",
		"json",
		"txt",
		"vista",
		"NvimTree",
		"git",
		"TelescopePrompt",
		"undotree",
		"flutterToolsOutline",
		"org",
		"orgagenda",
		"help",
		"startify",
		"dashboard",
		"packer",
		"neogitstatus",
		"NvimTree",
		"Trouble",
		"",
	}
}
