require("nvim-navic").setup({
	icons = {
		File          = " ",
		Module        = " ",
		Namespace     = " ",
		Package       = " ",
		Class         = " ",
		Method        = " ",
		Property      = " ",
		Field         = " ",
		Constructor   = " ",
		Enum          = "練",
		Interface     = "練",
		Function      = " ",
		Variable      = " ",
		Constant      = " ",
		String        = " ",
		Number        = " ",
		Boolean       = "◩ ",
		Array         = " ",
		Object        = " ",
		Key           = " ",
		Null          = "ﳠ ",
		EnumMember    = " ",
		Struct        = " ",
		Event         = " ",
		Operator      = " ",
		TypeParameter = " ",
	},
	highlight = true
})
